---
kind: pipeline
type: docker
name: testing
platform:
  os: linux
  arch: amd64
steps:

  - name: go vet
    image: 'golang:1.12'
    commands:
      - go vet ./...
    volumes:
      - name: gopath
        path: /go

  - name: go test
    image: 'golang:1.12'
    commands:
      - go test -cover ./...
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

trigger:
  event:
    - push
  branch:
    - development
---
kind: pipeline
type: docker
name: linux-amd64
platform:
  os: linux
  arch: amd64

steps:

  - name: build (push)
    image: 'golang:1.12'
    environment:
      CGO_ENABLED: '0'
    commands:
      - >-
        go build -v -ldflags "-X main.version=${DRONE_COMMIT_SHA:0:8}" -a -tags
        netgo -o release/linux/amd64/drone-ansible
    when:
      event:
        exclude:
          - tag

  - name: build (tag)
    image: 'golang:1.12'
    environment:
      CGO_ENABLED: '0'
    commands:
      - >-
        go build -v -ldflags "-X main.version=${DRONE_TAG##v}" -a -tags netgo -o
        release/linux/amd64/drone-ansible
    when:
      event:
        - tag

  - name: test executable
    image: 'golang:1.12'
    commands:
      - ./release/linux/amd64/drone-ansible --help


  - name: docker build and push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      dockerfile: docker/Dockerfile.linux.amd64
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - ${DRONE_BRANCH}-latest
    commands:
      - tags.sh $(cat ../VERSION) > .tags
      - cat .tags
    when:
      event:
        - push

depends_on:
  - testing
trigger:
  event:
    - push
  branch:
    - development
...
