---
kind: pipeline
type: docker
name: testing
platform:
  os: linux
  arch: amd64
steps:

  - name: go vet
    image: 'golang:1.12'
    commands:
      - go vet ./...
    volumes:
      - name: gopath
        path: /go

  - name: go test
    image: 'golang:1.12'
    commands:
      - go test -cover ./...
    volumes:
      - name: gopath
        path: /go

volumes:
  - name: gopath
    temp: {}

trigger:
  event:
    - push
  branch:
    - development
---
kind: pipeline
type: docker
name: linux-amd64
platform:
  os: linux
  arch: amd64

steps:

  - name: go build
    image: 'golang:1.12'
    environment:
      CGO_ENABLED: '0'
    commands:
      - >-
        go build -v -ldflags "-X main.version=$(cat VERSION)" -a -tags
        netgo -o release/linux/amd64/drone-ansible
    when:
      event:
        exclude:
          - tag

  - name: test entrypoint
    image: 'golang:1.12'
    commands:
      - ./release/linux/amd64/drone-ansible --help

  - name: generate docker tags
    image: golang:1.14
    commands:
      - version=''
      - if [ $DRONE_BRANCH = 'development' ]; then version='-development'; fi
      - echo $version
      - ./tags.sh $(cat VERSION) $version > .tags


  - name: docker build and push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      dockerfile: docker/Dockerfile.linux.amd64
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
    when:
      event:
        - push

depends_on:
  - testing
trigger:
  event:
    - push
  branch:
    - development
    - stable
...
